@TodoApi_HostAddress = https://localhost:7065

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  //TodoItem
}

###
